format_version: v1.0
type: UniqueComponent
attributes: {id: FreeRTOS}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: FREERTOS_CPU_CLOCK_HZ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: FreeRTOS, value: '492000000'}
- type: ElementPosition
  attributes: {x: '5', y: '102', id: FreeRTOS}
