configName: sam_l21_xpro
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: ATSAML21J18B
projectName: ''
settings:
  PackageFilter: audio;bootloader;bootloader_apps_usb;bsp;core;core_apps_pic32mx;core_apps_pic32mz_w1;csp;csp_apps_sam_d21_da1;quick_docs;reference_apps;usb;usb_apps_device;usb_apps_dual_role;usb_apps_host;usb_apps_multi_controller
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: SAML21_DFP\3.7.217
